### ISSUE TITLE
Allow relative paths in `run.config` and `process.config`.

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys#143]
As a user I'd like to have the ability to give relative paths (relative to the project directory) in the `run.config` and the `process.config` files.

That way, projects are more portable from one user's computer to another one's.

**Comment by zuckerruebe** [comment]
Related issue with should be dealt with in the same go: https://github.com/SPF-OST/pytrnsys_gui/issues/59

**Comment by ahobeost** [comment]
The current assumption for the run.config file is that the project folder is the same as where the config file is located.
Thus, because this folder has to be provided to read the file, we could use that directly, instead of providing the absolute paths in the run.config.

Then, if we want to allow different files to be used, we could provide locations and/or names relative to the folder where run.config is located.
As these are given specific names by the GUI, I would recommend not making these mutable in the run.config.
